"""maintenances table

Revision ID: 338af81676ea
Revises: 428c2e139569
Create Date: 2022-01-17 15:34:49.510220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338af81676ea'
down_revision = '428c2e139569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['train.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_time'), 'maintenance', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_time'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###