"""railwagons table

Revision ID: 6df328274315
Revises: 6d0bfc3a2170
Create Date: 2021-12-12 21:47:39.513315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df328274315'
down_revision = '6d0bfc3a2170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railwagon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_traction', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('railwagon')
    # ### end Alembic commands ###
