"""trains table

Revision ID: d728114e6a3d
Revises: 898ad16ea203
Create Date: 2022-01-04 17:18:54.635360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd728114e6a3d'
down_revision = '898ad16ea203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('personwagon', sa.Column('train_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personwagon', 'train', ['train_id'], ['id'])
    op.add_column('railwagon', sa.Column('train_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'railwagon', 'train', ['train_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'railwagon', type_='foreignkey')
    op.drop_column('railwagon', 'train_id')
    op.drop_constraint(None, 'personwagon', type_='foreignkey')
    op.drop_column('personwagon', 'train_id')
    op.drop_table('train')
    # ### end Alembic commands ###
